#define ARRAY_SIZE 100

const char* tupac_brenda[ARRAY_SIZE] = {

    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_1",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_2",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_3",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_4",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_5",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_6",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_7",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_8",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_9",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_10",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_11",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_12",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_13",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_14",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_15",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_16",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_17",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_18",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_19",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_20",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_21",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_22",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_23",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_24",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_25",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_26",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_27",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_28",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_29",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_30",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_31",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_32",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_33",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_34",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_35",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_36",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_37",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_38",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_39",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_40",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_41",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_42",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_43",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_44",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_45",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_46",
    "songs/2PacalypseNow/Brenda's Got A Baby/tupac_brenda_47"
};

const char* tupac_rebel[ARRAY_SIZE] = {
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_1",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_2",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_3",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_4",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_5",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_6",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_7",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_8",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_9",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_10",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_11",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_12",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_13",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_14",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_15",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_16",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_17",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_18",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_19",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_20",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_21",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_22",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_23",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_24",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_25",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_26",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_27",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_28",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_29",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_30",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_31",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_32",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_33",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_34",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_35",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_36",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_37",
    "songs/2PacalypseNow/Rebel of the Underground/2pac_rebel_38"
};

const char* tupac_keepyahead[ARRAY_SIZE] = {

    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_1",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_2",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_3",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_4",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_5",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_6",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_7",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_8",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_9",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_10",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_11",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_12",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_13",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_14",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_15",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_16",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_17",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_18",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_19",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_20",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_21",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_22",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_23",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_24",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_25",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_26",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_27",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_28",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_29",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_30",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_31",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_32",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_33",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_34",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_35",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_36",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_37",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_38",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_39",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_40",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_41",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_42",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_43",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_44",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_45",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_46",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_47",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_48",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_49",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_50",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_51",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_52",
    "songs/Stricly 4 My Niggas/Keep Ya Head Up/2pac_keepyahead_53"
};

const char* tupac_getaround[ARRAY_SIZE] = {

    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_1",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_2",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_3",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_4",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_5",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_6",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_7",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_8",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_9",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_10",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_11",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_12",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_12",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_13",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_14",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_15",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_16",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_17",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_18",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_19",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_20",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_21",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_22",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_23",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_24",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_25",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_26",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_27",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_28",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_29",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_30",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_31",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_32",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_33",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_34",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_35",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_36",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_37",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_38",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_39",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_40",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_41",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_42",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_43",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_44",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_45",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_46",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_47",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_48",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_49",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_50",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_51",
    "songs/Stricly 4 My Niggas/I Get Around/2pac_getaround_52"

};

const char* tupac_buryg[ARRAY_SIZE] = {

    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_1",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_2",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_3",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_4",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_5",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_6",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_7",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_8",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_9",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_10",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_11",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_12",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_13",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_14",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_15",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_16",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_17",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_18",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_19",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_20",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_21",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_22",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_23",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_24",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_25",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_26",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_27",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_28",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_29",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_30",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_31",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_32",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_33",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_34",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_35",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_36",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_37",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_38",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_39",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_40",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_41",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_42",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_43",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_44",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_45",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_46",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_47",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_48",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_49",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_50",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_51",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_52",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_53",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_54",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_55",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_56",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_57",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_58",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_59",
    "songs/Thug Life_Vol 1/Bury Me A G/2pac_buryg_60",
};

const char* tupac_liquor[ARRAY_SIZE] = {

    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_1",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_2",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_3",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_4",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_5",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_6",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_7",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_8",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_9",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_10",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_11",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_12",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_13",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_14",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_15",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_16",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_17",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_18",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_19",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_20",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_21",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_22",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_23",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_24",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_25",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_26",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_27",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_28",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_29",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_30",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_31",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_32",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_33",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_34",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_35",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_36",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_37",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_38",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_39",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_40",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_41",
    "songs/Thug Life_Vol 1/Pour Out A Little Liquor/2pac_liquor_42"
};

const char* tupac_mama[ARRAY_SIZE] = {
    "songs/Me Against The World/Dear Mama/2pac_mama_1",
    "songs/Me Against The World/Dear Mama/2pac_mama_2",
    "songs/Me Against The World/Dear Mama/2pac_mama_3",
    "songs/Me Against The World/Dear Mama/2pac_mama_4",
    "songs/Me Against The World/Dear Mama/2pac_mama_5",
    "songs/Me Against The World/Dear Mama/2pac_mama_6",
    "songs/Me Against The World/Dear Mama/2pac_mama_7",
    "songs/Me Against The World/Dear Mama/2pac_mama_8",
    "songs/Me Against The World/Dear Mama/2pac_mama_9",
    "songs/Me Against The World/Dear Mama/2pac_mama_10",
    "songs/Me Against The World/Dear Mama/2pac_mama_11",
    "songs/Me Against The World/Dear Mama/2pac_mama_12",
    "songs/Me Against The World/Dear Mama/2pac_mama_13",
    "songs/Me Against The World/Dear Mama/2pac_mama_14",
    "songs/Me Against The World/Dear Mama/2pac_mama_15",
    "songs/Me Against The World/Dear Mama/2pac_mama_16",
    "songs/Me Against The World/Dear Mama/2pac_mama_17",
    "songs/Me Against The World/Dear Mama/2pac_mama_18",
    "songs/Me Against The World/Dear Mama/2pac_mama_19",
    "songs/Me Against The World/Dear Mama/2pac_mama_20",
    "songs/Me Against The World/Dear Mama/2pac_mama_21",
    "songs/Me Against The World/Dear Mama/2pac_mama_22",
    "songs/Me Against The World/Dear Mama/2pac_mama_23",
    "songs/Me Against The World/Dear Mama/2pac_mama_24",
    "songs/Me Against The World/Dear Mama/2pac_mama_25",
    "songs/Me Against The World/Dear Mama/2pac_mama_26",
    "songs/Me Against The World/Dear Mama/2pac_mama_27",
    "songs/Me Against The World/Dear Mama/2pac_mama_28",
    "songs/Me Against The World/Dear Mama/2pac_mama_29",
    "songs/Me Against The World/Dear Mama/2pac_mama_30",
    "songs/Me Against The World/Dear Mama/2pac_mama_31",
    "songs/Me Against The World/Dear Mama/2pac_mama_32",
    "songs/Me Against The World/Dear Mama/2pac_mama_33",
    "songs/Me Against The World/Dear Mama/2pac_mama_34",
    "songs/Me Against The World/Dear Mama/2pac_mama_35",
    "songs/Me Against The World/Dear Mama/2pac_mama_36",
    "songs/Me Against The World/Dear Mama/2pac_mama_37",
    "songs/Me Against The World/Dear Mama/2pac_mama_38",
    "songs/Me Against The World/Dear Mama/2pac_mama_39",
    "songs/Me Against The World/Dear Mama/2pac_mama_40",
    "songs/Me Against The World/Dear Mama/2pac_mama_41",
    "songs/Me Against The World/Dear Mama/2pac_mama_42",
    "songs/Me Against The World/Dear Mama/2pac_mama_43",
    "songs/Me Against The World/Dear Mama/2pac_mama_44",
    "songs/Me Against The World/Dear Mama/2pac_mama_45",
    "songs/Me Against The World/Dear Mama/2pac_mama_46",
    "songs/Me Against The World/Dear Mama/2pac_mama_47",
    "songs/Me Against The World/Dear Mama/2pac_mama_48",
    "songs/Me Against The World/Dear Mama/2pac_mama_49",
    "songs/Me Against The World/Dear Mama/2pac_mama_50",
    "songs/Me Against The World/Dear Mama/2pac_mama_51",
    "songs/Me Against The World/Dear Mama/2pac_mama_52",
    "songs/Me Against The World/Dear Mama/2pac_mama_53",
    "songs/Me Against The World/Dear Mama/2pac_mama_54",
    "songs/Me Against The World/Dear Mama/2pac_mama_55",
    "songs/Me Against The World/Dear Mama/2pac_mama_56"
};

const char* tupac_ftw[ARRAY_SIZE] = {
    "songs/Me Against The World/Fuck The World/2pac_ftw_1",
    "songs/Me Against The World/Fuck The World/2pac_ftw_2",
    "songs/Me Against The World/Fuck The World/2pac_ftw_3",
    "songs/Me Against The World/Fuck The World/2pac_ftw_4",
    "songs/Me Against The World/Fuck The World/2pac_ftw_5",
    "songs/Me Against The World/Fuck The World/2pac_ftw_6",
    "songs/Me Against The World/Fuck The World/2pac_ftw_7",
    "songs/Me Against The World/Fuck The World/2pac_ftw_8",
    "songs/Me Against The World/Fuck The World/2pac_ftw_9",
    "songs/Me Against The World/Fuck The World/2pac_ftw_10",
    "songs/Me Against The World/Fuck The World/2pac_ftw_11",
    "songs/Me Against The World/Fuck The World/2pac_ftw_12",
    "songs/Me Against The World/Fuck The World/2pac_ftw_13",
    "songs/Me Against The World/Fuck The World/2pac_ftw_14",
    "songs/Me Against The World/Fuck The World/2pac_ftw_15",
    "songs/Me Against The World/Fuck The World/2pac_ftw_16",
    "songs/Me Against The World/Fuck The World/2pac_ftw_17",
    "songs/Me Against The World/Fuck The World/2pac_ftw_18",
    "songs/Me Against The World/Fuck The World/2pac_ftw_19",
    "songs/Me Against The World/Fuck The World/2pac_ftw_20",
    "songs/Me Against The World/Fuck The World/2pac_ftw_21",
    "songs/Me Against The World/Fuck The World/2pac_ftw_22",
    "songs/Me Against The World/Fuck The World/2pac_ftw_23",
    "songs/Me Against The World/Fuck The World/2pac_ftw_24",
    "songs/Me Against The World/Fuck The World/2pac_ftw_25",
    "songs/Me Against The World/Fuck The World/2pac_ftw_26",
    "songs/Me Against The World/Fuck The World/2pac_ftw_27",
    "songs/Me Against The World/Fuck The World/2pac_ftw_28",
    "songs/Me Against The World/Fuck The World/2pac_ftw_29",
    "songs/Me Against The World/Fuck The World/2pac_ftw_30",
    "songs/Me Against The World/Fuck The World/2pac_ftw_31",
    "songs/Me Against The World/Fuck The World/2pac_ftw_32",
    "songs/Me Against The World/Fuck The World/2pac_ftw_33",
    "songs/Me Against The World/Fuck The World/2pac_ftw_34",
    "songs/Me Against The World/Fuck The World/2pac_ftw_35",
    "songs/Me Against The World/Fuck The World/2pac_ftw_36",
    "songs/Me Against The World/Fuck The World/2pac_ftw_37",
    "songs/Me Against The World/Fuck The World/2pac_ftw_38",
    "songs/Me Against The World/Fuck The World/2pac_ftw_39",
    "songs/Me Against The World/Fuck The World/2pac_ftw_40",
    "songs/Me Against The World/Fuck The World/2pac_ftw_41",
    "songs/Me Against The World/Fuck The World/2pac_ftw_42",
    "songs/Me Against The World/Fuck The World/2pac_ftw_43",
    "songs/Me Against The World/Fuck The World/2pac_ftw_44",
    "songs/Me Against The World/Fuck The World/2pac_ftw_45",
    "songs/Me Against The World/Fuck The World/2pac_ftw_46",
    "songs/Me Against The World/Fuck The World/2pac_ftw_47",
    "songs/Me Against The World/Fuck The World/2pac_ftw_48",
    "songs/Me Against The World/Fuck The World/2pac_ftw_49",
    "songs/Me Against The World/Fuck The World/2pac_ftw_50",
    "songs/Me Against The World/Fuck The World/2pac_ftw_51"
};